version: '3'

services:
  user_db:
    image: postgres:13

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    networks:
      - app-network

  order_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    networks:
      - app-network

  user_service:
    build: ./user_service
    environment:
      DB_URL: postgresql+asyncpg://postgres:postgres@user_db:5432/user_db
    ports:
      - "8000:8000"
    volumes:
      - ./shared:/app/shared
    networks:
      - app-network

  order_service:
    build: ./order_service
    environment:
      DB_URL: postgresql+asyncpg://postgres:postgres@order_db:5432/order_db
    ports:
      - "8001:8001"
    volumes:
      - ./shared:/app/shared
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
