"""add UniqueConstraint user_id and order_name

Revision ID: cbdbbc619514
Revises: 511ee20530b0
Create Date: 2024-07-12 19:11:55.535987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbdbbc619514'
down_revision: Union[str, None] = '511ee20530b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_order_name_key', 'orders', type_='unique')
    op.create_unique_constraint('_user_order_uc', 'orders', ['user_id', 'order_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_order_uc', 'orders', type_='unique')
    op.create_unique_constraint('orders_order_name_key', 'orders', ['order_name'])
    # ### end Alembic commands ###
