version: "3.0"
services:
  db:
    container_name: "user"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_db
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge